// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     application_update_available.avsc
 *     application_version_available.avsc
 *     application_version_installed.avsc
 */

package avro

import (
	"io"
)

type ApplicationVersionInstalled struct {
	App     string
	Version string
	Url     string
}

func DeserializeApplicationVersionInstalled(r io.Reader) (*ApplicationVersionInstalled, error) {
	return readApplicationVersionInstalled(r)
}

func NewApplicationVersionInstalled() *ApplicationVersionInstalled {
	v := &ApplicationVersionInstalled{}

	return v
}

func (r *ApplicationVersionInstalled) Schema() string {
	return "{\"fields\":[{\"name\":\"App\",\"type\":\"string\"},{\"name\":\"Version\",\"type\":\"string\"},{\"name\":\"Url\",\"type\":\"string\"}],\"name\":\"ApplicationVersionInstalled\",\"type\":\"record\"}"
}

func (r *ApplicationVersionInstalled) Serialize(w io.Writer) error {
	return writeApplicationVersionInstalled(r, w)
}
