// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     application_update_available.avsc
 *     application_version_available.avsc
 *     application_version_installed.avsc
 */

package avro

import (
	"fmt"
	"io"
	"math"
)

type ByteWriter interface {
	Grow(int)
	WriteByte(byte) error
}

type StringWriter interface {
	WriteString(string) (int, error)
}

func encodeInt(w io.Writer, byteCount int, encoded uint64) error {
	var err error
	var bb []byte
	bw, ok := w.(ByteWriter)
	// To avoid reallocations, grow capacity to the largest possible size
	// for this integer
	if ok {
		bw.Grow(byteCount)
	} else {
		bb = make([]byte, 0, byteCount)
	}

	if encoded == 0 {
		if bw != nil {
			err = bw.WriteByte(0)
			if err != nil {
				return err
			}
		} else {
			bb = append(bb, byte(0))
		}
	} else {
		for encoded > 0 {
			b := byte(encoded & 127)
			encoded = encoded >> 7
			if !(encoded == 0) {
				b |= 128
			}
			if bw != nil {
				err = bw.WriteByte(b)
				if err != nil {
					return err
				}
			} else {
				bb = append(bb, b)
			}
		}
	}
	if bw == nil {
		_, err := w.Write(bb)
		return err
	}
	return nil

}

func readApplicationUpdateAvailable(r io.Reader) (*ApplicationUpdateAvailable, error) {
	var str = &ApplicationUpdateAvailable{}
	var err error
	str.App, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Version, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Url, err = readString(r)
	if err != nil {
		return nil, err
	}

	return str, nil
}

func readApplicationVersionAvailable(r io.Reader) (*ApplicationVersionAvailable, error) {
	var str = &ApplicationVersionAvailable{}
	var err error
	str.App, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Version, err = readString(r)
	if err != nil {
		return nil, err
	}

	return str, nil
}

func readApplicationVersionInstalled(r io.Reader) (*ApplicationVersionInstalled, error) {
	var str = &ApplicationVersionInstalled{}
	var err error
	str.App, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Version, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Url, err = readString(r)
	if err != nil {
		return nil, err
	}

	return str, nil
}

func readLong(r io.Reader) (int64, error) {
	var v uint64
	buf := make([]byte, 1)
	for shift := uint(0); ; shift += 7 {
		if _, err := io.ReadFull(r, buf); err != nil {
			return 0, err
		}
		b := buf[0]
		v |= uint64(b&127) << shift
		if b&128 == 0 {
			break
		}
	}
	datum := (int64(v>>1) ^ -int64(v&1))
	return datum, nil
}

func readString(r io.Reader) (string, error) {
	len, err := readLong(r)
	if err != nil {
		return "", err
	}

	// makeslice can fail depending on available memory.
	// We arbitrarily limit string size to sane default (~2.2GB).
	if len < 0 || len > math.MaxInt32 {
		return "", fmt.Errorf("string length out of range: %d", len)
	}

	bb := make([]byte, len)
	_, err = io.ReadFull(r, bb)
	if err != nil {
		return "", err
	}
	return string(bb), nil
}

func writeApplicationUpdateAvailable(r *ApplicationUpdateAvailable, w io.Writer) error {
	var err error
	err = writeString(r.App, w)
	if err != nil {
		return err
	}
	err = writeString(r.Version, w)
	if err != nil {
		return err
	}
	err = writeString(r.Url, w)
	if err != nil {
		return err
	}

	return nil
}
func writeApplicationVersionAvailable(r *ApplicationVersionAvailable, w io.Writer) error {
	var err error
	err = writeString(r.App, w)
	if err != nil {
		return err
	}
	err = writeString(r.Version, w)
	if err != nil {
		return err
	}

	return nil
}
func writeApplicationVersionInstalled(r *ApplicationVersionInstalled, w io.Writer) error {
	var err error
	err = writeString(r.App, w)
	if err != nil {
		return err
	}
	err = writeString(r.Version, w)
	if err != nil {
		return err
	}
	err = writeString(r.Url, w)
	if err != nil {
		return err
	}

	return nil
}

func writeLong(r int64, w io.Writer) error {
	downShift := uint64(63)
	encoded := uint64((r << 1) ^ (r >> downShift))
	const maxByteSize = 10
	return encodeInt(w, maxByteSize, encoded)
}

func writeString(r string, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil {
		return err
	}
	if sw, ok := w.(StringWriter); ok {
		_, err = sw.WriteString(r)
	} else {
		_, err = w.Write([]byte(r))
	}
	return err
}
